### ISSUE TITLE
Not receiving sound notifications

### ISSUE THREAD

**Issue by CarlosCraveiro** [luisnquin/battery-notifier#3]
I'm not receiving sound notifications. Most likely because of this error I'm getting from _soloud_.

```bash
[2024-04-02T01:41:23Z ERROR battery_notifier::notify] [ERROR] soloud instance couldn't be correctly initialized: An internal error occured UnknownError
```

I'm current running a NixOS 24.05.20240323.d936a21 (Uakari) x86_64.

![Bug_with_soloud](https://github.com/luisnquin/battery-notifier/assets/85318248/f187001c-d44c-4fd0-a6e0-330c857f9269)

**Comment by luisnquin** [comment]
Hello @CarlosCraveiro, thank you for your interest in the project.

Some months ago, I encountered a similar issue when events like these were triggered. Despite initially thinking I had resolved the error after some struggle with the library, it appears that may not be the case. The error message from Souloud is not entirely clear, prompting me to consider either switching to another library or updating the sound formats, which may be necessary for this library

 I'll start the research during the night because at the moment I'm writing this I'm having obstacles to use my computer :)))

**Comment by luisnquin** [comment]
Still, what audio backend are you using on your computer? This is probably part of the bug

https://github.com/MoAlyousef/soloud-rs?tab=readme-ov-file#supported-backends

**Comment by CarlosCraveiro** [comment]
> Still, what audio backend are you using on your computer? This is probably part of the bug
> 
> https://github.com/MoAlyousef/soloud-rs?tab=readme-ov-file#supported-backends

I'm currently with PulseAudio. Maybe that's why this bug is occurring...I'll see if I can do something about it through the day and then come back with news.

**Comment by luisnquin** [comment]
It would help me a lot. This also imply more documentation about the different backends and probably a home manager option to select an audio backend.

**Comment by CarlosCraveiro** [comment]
Hi! I managed to get the sound notifications to work on my computer!

Did I end up having to switch my audio backend to Pipewire? Yeah, but it was already something I intended to do. And with Pipewire I just needed to set the option to be compatible with Jack applications (one of the backends suported by soloud).

Below is the snippet of how my nix config turned out.
```nix
...
security.rtkit.enable = true;
    services.pipewire = {
        enable = true;
        alsa.enable = true;
        alsa.support32Bit = true;
        pulse.enable = true;
        jack.enable = true;
    };
...
```

**Comment by CarlosCraveiro** [comment]
And, taking the opportunity to comment on PR #4 ... I don't how to explain, but the system module I proposed is working. Including notifications and sounds!

I don't know how It is accessing lib-notify...maybe my configuration is very unusual...but at least I have visual and audible battery notifications!

The project is really cool and I loved it! Maybe I'll open issues suggesting features, but this will be something that will come later and after some digging through the code.

**Comment by luisnquin** [comment]
@CarlosCraveiro the audio is working now probably because you are using another backend :) it still doesn't meant no support for others, I'll try to do the necessary tasks to avoid this issue to happen again

About how the nixos module works, maybe I misunderstood something or as you said maybe you are using unusual configurations

But since the NixOS module is working, I'll add it to the flake for others to test in the same way

**Comment by luisnquin** [comment]
@CarlosCraveiro if you want to optimize, refactor or anything else just open a new PR but remind to use conventional commits to keep a consistent git history

**Comment by luisnquin** [comment]
Hey @CarlosCraveiro, it looks like the issue was resolved because the configuration was utilizing the `systemd.user.services` option instead of `systemd.services`

The key distinction is the location where the unit file was saved: **/etc/systemd/user/battery-notifier.service**

In this way the unit is always loaded within the user scope, maintaining everything functioning as expected.

I have prepared a NixOS options module that you can use now for future updates :)
Keep in mind that the option in the NixOS module is named as `services.battery-notifier.*`
